
DROP TABLE IF EXISTS restaurants CASCADE;
CREATE TABLE restaurants (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR (255) NOT NULL,
  username VARCHAR (50) NOT NULL,
  password VARCHAR (255) NOT NULL,
  phone_no VARCHAR (255) NOT NULL
);
